export const GAME_STATUS = {
  CROSS_TURN: "CROSS_TURN",
  NAUGHT_TURN: "NAUGHT_TURN",
  CROSS_WINS: "CROSS_WINS",
  NAUGHT_WINS: "NAUGHT_WINS",
  DRAW: "DRAW",
};

export const HTML_ELEMENTS = {
  MENU_VIEW: "MENU_VIEW",
  GAMEBOARD_VIEW: "GAMEBOARD_VIEW",
  SECOND_PLAYER_BUTTON: "SECOND_PLAYER_BUTTON",
  COMPUTER_PLAYER_BUTTON: "COMPUTER_PLAYER_BUTTON",
  ABORT_GAME_BUTTON: "ABORT_GAME_BUTTON",
  RESTART_GAME_BUTTON: "RESTART_GAME_BUTTON",
  PLAYGROUND: "PLAYGROUND",
  CELLS: "CELLS",
  TITLE: "TITLE",
};
