export const GAME_STATUS = {
  CROSS_TURN: "CROSS_TURN",
  NAUGHT_TURN: "NAUGHT_TURN",
  CROSS_WINS: "CROSS_WINS",
  NAUGHT_WINS: "NAUGHT_WINS",
  DRAW: "DRAW",
};

export const HTML_ELEMENTS = {
  MENU_VIEW: "MENU_VIEW",
  GAMEBOARD_VIEW: "GAMEBOARD_VIEW",
  SETTINGS_VIEW: "SETTINGS_VIEW",
  SECOND_PLAYER_BUTTON: "SECOND_PLAYER_BUTTON",
  COMPUTER_PLAYER_BUTTON: "COMPUTER_PLAYER_BUTTON",
  CANCEL_BUTTON: "CANCEL_BUTTON",
  PLAY_BUTTON: "PLAY_BUTTON",
  ABORT_GAME_BUTTON: "ABORT_GAME_BUTTON",
  RESTART_GAME_BUTTON: "RESTART_GAME_BUTTON",
  PLAYGROUND: "PLAYGROUND",
  CELLS: "CELLS",
  TITLE: "TITLE",
  SELECTED_MARK: "SELECTED_MARK",
  FIRST_MOVE: "FIRST_MOVE",
  GAME_DIFFICULTY: "GAME_DIFFICULTY",
};

export const SETTINGS_OPTION_TYPES = {
  SELECTED_MARK: "SELECTED_MARK",
  FIRST_MOVE: "FIRST_MOVE",
  GAME_DIFFICULTY: "GAME_DIFFICULTY",
};

export const SELECT_NAMES = {
  selectedMark: SETTINGS_OPTION_TYPES.SELECTED_MARK,
  firstMove: SETTINGS_OPTION_TYPES.FIRST_MOVE,
  gameDifficulty: SETTINGS_OPTION_TYPES.GAME_DIFFICULTY,
};

export const PLAY_MODE = {
  WITH_PLAYER: "WITH_PLAYER",
  WITH_COMPUTER: "WITH_COMPUTER",
};

export const BUTTON_TYPES = {
  SECOND_PLAYER: "SECOND_PLAYER",
  COMPUTER_PLAYER: "COMPUTER_PLAYER",
  PLAY: "PLAY",
  CANCEL: "CANCEL",
  RESTART: "RESTART",
  ABORT: "ABORT",
};

export const MARK_TYPES = {
  X: "X",
  O: "O",
};

export const TURN_TYPES = {
  PLAYER: "PLAYER",
  COMPUTER: "COMPUTER",
};

export const GAME_DIFFICULTY_TYPES = {
  BASIC: "BASIC",
  ADVANCED: "ADVANCED",
};
